export const EMAIL_REGEX =
  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export const MAX_LENGTH_PASSWORD = 6;

export const MONTH_OPTIONS = [
  "--",
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
];

export const YEAR_OPTIONS = ["--", "20", "21", "22", "23", "24", "25"];

export const COMMUNITIES_OPTIONS = [
  "Andalucía",
  "Aragón",
  "Asturias",
  "Islas Baleares",
  "Canarias",
  "Cantabria",
  "Castilla y León",
  "Castilla La Mancha",
  "Cataluña",
  "Comunidad Valenciana",
  "Extremadura",
  "Galicia",
  "Madrid",
  "Murcia",
  "Navarra",
  "País Vasco",
  "La Rioja",
];

export const PROVINCES_OPTIONS = [
  "Almería",
  "Cádiz",
  "Córdoba",
  "Granada",
  "Huelva",
  "Jaén",
  "Málaga",
  "Sevilla",
  "Huesca",
  "Teruel",
  "Zaragoza",
  "Asturias",
  "Islas Baleares",
  "Las Palmas",
  "S.Cruz de Tenerife",
  "Cantabria",
  "Ávila",
  "Burgos",
  "León",
  "Palencia",
  "Salamanca",
  "Segovia",
  "Soria",
  "Valladolid",
  "Zamora",
  "Albacete",
  "Ciudad Real",
  "Cuenca",
  "Guadalajara",
  "Toledo",
  "Barcelona",
  "Gerona",
  "Lérida",
  "Tarragona",
  "Alicante",
  "Castellón",
  "Valencia",
  "Badajoz",
  "Cáceres",
  "A Coruña",
  "Lugo",
  "Orense",
  "Pontevedra",
  "Madrid",
  "Murcia",
  "Navarra",
  "Álava",
  "Guipúzcoa",
  "Vizcaya",
  "La Rioja",
];

export const DEMARCATION_OPTIONS = [
  "Portero",
  "Lateral Derecho",
  "Lateral Izquierdo",
  "Defensa Central",
  "Libero",
  "Medio Centro Defensivo",
  "Medio Centro",
  "Medio Centro Ofensivo",
  "Interior Derecho",
  "Media Punta",
  "Extremo Derecho",
  "Extremo Izquierdo",
  "Delantero Centro",
  "Segundo Delantero",
];
